Repository dbetka/harcmap, pull requests merged in 2021-03, with the labels that each got.

#308 #301 Admin can see all point on map; Add new demo2@demo.com user
  config/mongodb/local.js
  src/map/createFeatures.js
  src/store/event.js
Labels: bug

#309 #282 Add actial map position to cookies
  src/components/organisms/map.vue
  src/store/event.js
Labels: improvement

#303 Issue/301/point details above map
  src/components/app.vue
  src/components/molecules/snackbar.vue
  src/components/organisms/map.vue
  src/components/organisms/popup/map.vue
  src/dictionary/language/pl.js
  src/index.js
  src/map/popup.js
  src/store/event.js
  src/store/index.js
  src/store/map-popup.js
  src/store/snackbar.js
  src/style/components/atoms/icon/list.sass
  src/style/components/atoms/icon/snackbar.sass
  src/style/components/molecules/list-element/popup.sass
  src/style/components/molecules/snackbar.sass
  src/style/components/organisms/popup/map.sass
  src/style/variables/colors/dark.sass
  src/style/variables/colors/light.sass
  src/utils/action.js
  src/utils/permissions.js
Labels: improvement

#316 #311 Fix error handler on signUp page
  src/components/pages/sign-up.vue
  src/dictionary/language/pl.js
  src/utils/macros/errors.js
Labels: bug

#317 #314 Fix menu height
  src/style/components/organisms/menu.sass
Labels: bug

#312 Issue/241/create collected points view for admin
  config/mongodb/local.js
  package.json
  src/api/mock/user-controller.js
  src/api/real/user-controller.js
  src/components/atoms/icon/category.vue
  src/components/atoms/icon/close-popup.vue
  src/components/molecules/circle-progress.vue
  src/components/molecules/row/category-sum.vue
  src/components/molecules/row/point.vue
  src/components/molecules/row/score.vue
  src/components/organisms/collected-points.vue
  src/components/organisms/header.vue
  src/components/organisms/menu.vue
  src/components/organisms/popup/score.vue
  src/components/pages/admin/panel.vue
  src/components/pages/admin/scoreboard.vue
  src/components/pages/collected-points.vue
  src/components/pages/error.vue
  src/components/pages/sign-in.vue
  src/components/pages/sign-up.vue
  src/dictionary/language/pl.js
  src/index.js
  src/router/routes.js
  src/store/all-users.js
  src/store/event.js
  src/store/event/points.js
  src/store/index.js
  src/store/theme.js
  src/style/components/atoms/icon/close-popup.sass
  src/style/components/atoms/message/error.sass
  src/style/components/atoms/message/table-error.sass
  src/style/components/molecules/cover.sass
  src/style/components/molecules/cover/popup.sass
  src/style/components/molecules/grid/score.sass
  src/style/components/organisms/popup.sass
  src/style/components/organisms/popup/score.sass
  src/style/features/text.sass
  src/style/features/text/colors.sass
  src/style/variables/colors/light.sass
  src/utils/macros/errors.js
  src/utils/macros/routes.js
  src/utils/permissions.js
Labels: improvement

#320 Issue/318/start page for admin
  src/components/pages/admin/start.vue
  src/components/pages/start.vue
  src/components/templates/start.vue
  src/dictionary/language/pl.js
  src/router/routes.js
  src/utils/macros/errors.js
Labels: improvement

#322 Issue/321/fix set default map position
  .eslintrc
  src/api/real/event-controller.js
  src/components/organisms/admin/set-map-position.vue
  src/components/organisms/map.vue
  src/map/index.js
  src/store/event.js
Labels: bug

#325 Issue/324/add time start and time end for timeout points
  bin/prepareEvent.js
  config/mongodb/local.js
  controllers/eventPoint.js
  controllers/eventPoints.js
  lib/validateCodes.js
  lib/validator.js
  public/iconfont/README.md
  src/api/mock/mockMethods/get-points.js
  src/components/atoms/icon/close-popup.vue
  src/components/molecules/table-row/temporary-points.vue
  src/components/organisms/collected-points.vue
  src/components/organisms/map.vue
  src/components/organisms/popup/map.vue
  src/components/organisms/popup/score.vue
  src/components/pages/admin/scoreboard.vue
  src/components/pages/temporary-points.vue
  src/components/pages/timeout-points.vue
  src/dictionary/language/pl.js
  src/map/createFeatures.js
  src/map/index.js
  src/map/popup.js
  src/router/routes.js
  src/store/event.js
  src/store/event/points.js
  src/structures/map-point.js
  src/style/components/atoms/icon/active-point.sass
  src/style/components/atoms/icon/close-popup-map.sass
  src/style/components/atoms/icon/disabled-point.sass
  src/style/components/atoms/icon/future-point.sass
  src/style/components/molecules/list-element/popup.sass
  src/style/components/organisms/popup/map.sass
  src/utils/auto-update.js
  src/utils/macros.js
  src/utils/macros/map-point-types.js
  temporary-points.js
Labels: improvement

#333 Fix bug collect point with is collected by another user
  README.md
  controllers/pointCollect.js
  lib/validateCodes.js
  src/dictionary/language/pl.js
  src/utils/macros/errors.js
Labels: bug

#335 #295 Fix point validation while collecting
  controllers/pointCollect.js
Labels: bug

#340 Issue/339/add snackbars for forms messages
  src/components/mixins/base.js
  src/components/mixins/form.js
  src/components/molecules/snackbar.vue
  src/components/pages/admin/edit-event.vue
  src/components/pages/change-password.vue
  src/components/pages/collect-point.vue
  src/components/pages/remind-password.vue
  src/components/pages/sign-in.vue
  src/components/pages/sign-up.vue
  src/dictionary/language/pl.js
  src/store/snackbar.js
  src/style/components/molecules/snackbar.sass
  src/style/components/molecules/snackbar/error.sass
  src/style/components/molecules/snackbar/success.sass
Labels: improvement

#344 Issue/338/add date to timeout points
  src/components/molecules/table-row/temporary-points.vue
  src/components/pages/timeout-points.vue
  src/style/components/molecules/banner-timer.sass
  src/style/components/molecules/countdown-time/countdown-timer.sass
  temporary-points.js
Labels: bug, improvement

#319 Issue/313/point id should be easy to read
  bin/prepareEvent.js
  config/mongodb/local.js
  lib/utils.js
  lib/validateCodes.js
  lib/validator.js
  src/store/point.js
  src/utils/random.js
  vendors/random.js
  vendors/validate-tools.js
Labels: bug

#337 Issue/336/add the end date of the event
  bin/prepareEvent.js
  config/mongodb/local.js
  controllers/event.js
  controllers/pointCollect.js
  controllers/user/login.js
  lib/validateCodes.js
  lib/validator.js
  src/api/real/event-controller.js
  src/components/molecules/field/date.vue
  src/components/pages/admin/edit-event.vue
  src/components/pages/admin/start.vue
  src/components/pages/start.vue
  src/components/templates/start.vue
  src/dictionary/language/pl.js
  src/store/event.js
  src/structures/app-event.js
  src/utils/macros/errors.js
Labels: improvement

#326 Add endpoint to allow download points in csv format
  app.js
  controllers/point/all.js
  controllers/point/index.js
  controllers/user/all.js
  middleware/permissions.js
  package.json
  spec/swagger.js
  src/components/pages/admin/panel.vue
Labels: current

#350 Issue/345/add start event date
  bin/prepareEvent.js
  config/mongodb/local.js
  controllers/event.js
  controllers/pointCollect.js
  lib/validateCodes.js
  lib/validator.js
  src/api/real/event-controller.js
  src/components/pages/admin/edit-event.vue
  src/components/pages/timeout-points.vue
  src/components/templates/start.vue
  src/dictionary/language/pl.js
  src/store/event.js
  src/structures/app-event.js
  src/utils/event.js
  src/utils/macros/errors.js
Labels: improvement, security

#353 Issue/352/correct error messages on sign in
  src/components/pages/sign-in.vue
  src/map/createFeatures.js
  src/map/createLinesFeature.js
  src/store/user.js
  src/utils/api-response-service.js
  src/utils/error-message.js
  src/utils/style-manager.js
Labels: bug

#354 Issue/346/release v1.2.0
  CHANGELOG.md
  package.json
Labels: documentation

#356 #355 Fix datetime fields width
  src/style/components/atoms/field.sass
Labels: bug

#358 Issue/357/admin cannot see points before start event
  lib/validator.js
  src/components/organisms/menu.vue
  src/store/event.js
  src/style/components/atoms/version.sass
Labels: bug

#360 #359 Fix position on init for set-point-position view
  src/components/organisms/admin/set-point-position.vue
  src/map/config.js
  src/map/index.js
Labels: bug

#362 Issue/361/bug on edit point position
  src/components/molecules/banner-map.vue
  src/components/molecules/map-pointer.vue
  src/components/molecules/select.vue
  src/components/organisms/admin/set-map-position.vue
  src/components/organisms/admin/set-point-position.vue
  src/components/organisms/float-container.vue
  src/components/organisms/map.vue
  src/components/pages/admin/edit-event.vue
  src/components/pages/admin/edit-point.vue
  src/components/pages/admin/new-point.vue
  src/components/pages/admin/panel.vue
  src/components/pages/admin/set-map-position.vue
  src/components/pages/admin/set-point-position.vue
  src/components/pages/sign-in.vue
  src/components/templates/event-form.vue
  src/components/templates/point-form.vue
  src/dictionary/language/pl.js
  src/router/routes.js
  src/store/event.js
  src/store/index.js
  src/store/point.js
  src/style/components/molecules/map-pointer.sass
  src/style/components/organisms/float-container.sass
  src/utils/id.js
  src/utils/macros/routes.js
Labels: bug

#364 Issue/363/show user when new position of map and point is chosen
  src/components/molecules/banner-map.vue
  src/components/organisms/admin/set-map-position.vue
  src/components/organisms/admin/set-point-position.vue
  src/components/templates/event-form.vue
  src/components/templates/point-form.vue
  src/dictionary/language/pl.js
  src/map/index.js
  src/router/routes.js
  src/style/components/atoms/button/icon/icon-inside.sass
  src/style/components/atoms/button/icon/size-36.sass
  src/style/components/atoms/icon/footer/big.sass
  src/style/components/organisms/footer.sass
  src/style/components/organisms/header.sass
  src/utils/macros/routes.js
Labels: improvement

#366 Issue/365/add functionality to remove points
  src/components/mixins/form.js
  src/components/organisms/popup/map.vue
  src/components/pages/about.vue
  src/dictionary/language/pl.js
  src/store/event/points.js
  src/utils/communicates.js
  src/utils/error-message.js
Labels: improvement

#368 #367 Change collected points appearance
  src/map/createFeatures.js
Labels: bug, improvement

#385 Issue/370/show welcome message on first login
  config/mongodb/local.js
  controllers/user/login.js
  controllers/user/user.js
  lib/passportConfig.js
  package.json
  src/components/app.vue
  src/components/atoms/link-menu.vue
  src/components/molecules/slide.vue
  src/components/organisms/guide.vue
  src/components/organisms/menu.vue
  src/components/pages/sign-in.vue
  src/dictionary/language/pl.js
  src/store/event.js
  src/store/guide.js
  src/store/index.js
  src/store/user.js
  src/style/components/atoms/icon/close-popup.sass
  src/style/components/atoms/text/title/size-28.sass
  src/style/components/molecules/slide.sass
  src/style/dark.sass
  src/style/external-components.sass
  src/style/light.sass
  src/utils/macros/routes.js
Labels: improvement

#386 issue/380/Wrong-start-page-after-change-account-type
  src/components/pages/admin/start.vue
  src/components/pages/start.vue
  src/router/routes.js
Labels: bug

#387 issue/376/Add-instruction-how-to-release-version
  README.md
Labels: documentation, improvement

#388 Issue/383/correct scoreboard appearance
  config/mongodb/local.js
  src/components/pages/admin/scoreboard.vue
Labels: bug, improvement

#389 issue/384/Menu-should-handle-slide-event
  package.json
  src/components/app.vue
  src/components/organisms/menu.vue
  src/index.js
Labels: improvement

#390 Issue/221/safe icons script against name change
  bin/clone-material-icons.js
  bin/create-list-of-icons.js
  lib/icon-list-generator.js
  package.json
  public/iconfont/MaterialIcons-Regular.codepoints
  public/iconfont/MaterialIcons-Regular.ttf
  public/iconfont/MaterialIconsOutlined-Regular.codepoints
  public/iconfont/MaterialIconsOutlined-Regular.otf
  public/iconfont/MaterialIconsRound-Regular.codepoints
  public/iconfont/MaterialIconsRound-Regular.otf
  public/iconfont/MaterialIconsSharp-Regular.codepoints
  public/iconfont/MaterialIconsSharp-Regular.otf
  public/iconfont/MaterialIconsTwoTone-Regular.codepoints
  public/iconfont/MaterialIconsTwoTone-Regular.otf
  public/iconfont/README.md
  src/__jscash__/icons-names-list.js
  src/index.html
  src/style/dark.sass
  src/style/fonts.sass
  src/style/light.sass
  vendors/console-colors.js
Labels: improvement, refactor, security

#393 #392 Catch server connection error
  src/dictionary/language/pl.js
  src/utils/api-response-service.js
Labels: bug

#395 Issue/394/move first login field to cookies
  config/mongodb/local.js
  controllers/user/login.js
  controllers/user/user.js
  lib/passportConfig.js
  src/components/pages/sign-in.vue
  src/store/user.js
  src/utils/first-login.js
Labels: improvement, refactor

#397 Issue/396/update list of points and fix little bugs
  bin/prepareEvent.js
  points-old.js
  points.js
  src/components/organisms/map.vue
  src/map/popup.js
  temporary-points.js
Labels: bug, improvement

#399 Issue/398/add points searcher for admin
  package.json
  src/components/pages/admin/panel.vue
  src/components/pages/admin/search-point.vue
  src/dictionary/language/pl.js
  src/router/routes.js
  src/store/theme.js
  src/style/components/atoms/button/icon/minimal.sass
  src/style/components/molecules/grid/search-point.sass
  src/utils/macros/routes.js
Labels: current, improvement

#401 Issue/400/add limited permissions field for admin
  config/mongodb/local.js
  controllers/user/login.js
  controllers/user/user.js
  lib/passportConfig.js
  src/components/atoms/button/fill/primary.vue
  src/components/atoms/button/fill/secondary.vue
  src/components/organisms/footer.vue
  src/components/organisms/header.vue
  src/components/organisms/menu.vue
  src/components/organisms/popup/map.vue
  src/components/pages/admin/panel.vue
  src/components/pages/admin/search-point.vue
  src/components/pages/start.vue
  src/dictionary/language/pl.js
  src/index.js
  src/router/index.js
  src/router/routes.js
  src/store/user.js
  src/style/features/overflow.sass
  src/style/variables.sass
  src/utils/macros/routes.js
  src/utils/permissions.js
Labels: improvement, security

#402 Issue/378/error 404 after click on activation link
  controllers/user/activation.js
  src/components/organisms/header.vue
  src/components/pages/activation-done.vue
  src/components/pages/activation-wrong.vue
  src/components/pages/sign-up.vue
  src/dictionary/language/pl.js
  src/router/routes.js
  src/utils/macros/errors.js
  src/utils/macros/routes.js
Labels: bug, improvement, refactor

#404 #403 Block menu open before login
  src/components/app.vue
Labels: bug

#372 issue/371/Release v1.2.1
  CHANGELOG.md
  package.json
Labels: documentation

#406 Release V1.2.1
  CHANGELOG.md
  lib/validator.js
  package.json
  src/components/mixins/form.js
  src/components/molecules/banner-map.vue
  src/components/molecules/map-pointer.vue
  src/components/molecules/select.vue
  src/components/organisms/admin/set-map-position.vue
  src/components/organisms/admin/set-point-position.vue
  src/components/organisms/float-container.vue
  src/components/organisms/map.vue
  src/components/organisms/menu.vue
  src/components/organisms/popup/map.vue
  src/components/pages/about.vue
  src/components/pages/admin/edit-event.vue
  src/components/pages/admin/edit-point.vue
  src/components/pages/admin/new-point.vue
  src/components/pages/admin/panel.vue
  src/components/pages/admin/set-map-position.vue
  src/components/pages/admin/set-point-position.vue
  src/components/pages/sign-in.vue
  src/components/templates/event-form.vue
  src/components/templates/point-form.vue
  src/dictionary/language/pl.js
  src/map/config.js
  src/map/createFeatures.js
  src/map/index.js
  src/router/routes.js
  src/store/event.js
  src/store/event/points.js
  src/store/index.js
  src/store/point.js
  src/style/components/atoms/button/icon/icon-inside.sass
  src/style/components/atoms/button/icon/size-36.sass
  src/style/components/atoms/field.sass
  src/style/components/atoms/icon/footer/big.sass
  src/style/components/atoms/version.sass
  src/style/components/molecules/map-pointer.sass
  src/style/components/organisms/float-container.sass
  src/style/components/organisms/footer.sass
  src/style/components/organisms/header.sass
  src/utils/communicates.js
  src/utils/error-message.js
  src/utils/id.js
  src/utils/macros/routes.js
Labels: documentation

#369 Issue/332/create warn field in request responses
  controllers/point/all.js
  controllers/user/all.js
  controllers/user/login.js
  controllers/user/remind.js
  controllers/user/user.js
  lib/endpoint.js
  lib/passportConfig.js
  lib/security/loginOnMultipleDevices.js
  lib/utils.js
  lib/validateCodes.js
  middleware/permissions.js
  spec/swagger/components/responses.yaml
  src/api/real/user-controller.js
  src/components/molecules/row/point.vue
  src/dictionary/language/pl.js
  src/utils/api-response-service.js
  src/utils/auto-update.js
  src/utils/macros/errors.js
  src/utils/request.js
  src/utils/warn-message.js
  temporary-points.js
Labels: improvement, security

#408 #407 Bump version v1.2.2
  CHANGELOG.md
  package.json
Labels: documentation

#412 Enable cross device login for admin
  lib/security/loginOnMultipleDevices.js
Labels: current, improvement

#416 #391 Fix main button appearance on Safari
  src/style/components/atoms/icon/footer/big.sass
Labels: bug

#417 issue/415/Correct-clock-appearance-on-timeout-point-page
  src/components/molecules/clock.vue
  src/style/components/atoms/icon/clock.sass
  src/style/components/molecules/clock.sass
  src/style/components/molecules/grid/temporary-points.sass
Labels: improvement

#413 Prevent emails from going to spam
  controllers/user/remind.js
  controllers/user/user.js
  lib/mail.js
  lib/mail/mail.js
  lib/mail/mailHtmlContent.js
Labels: bug

#422 Issue/421/separate vendors from main bundle
  package.json
  webpack.common.js
Labels: improvement, performance, refactor

#424 Issue/432/add covid info to guide
  src/components/organisms/guide.vue
  src/dictionary/language/pl.js
Labels: improvement

#426 #425 Fix footer appearance on android
  src/style/components/organisms/footer.sass
Labels: bug

#427 #414 Fix remind password route configuration
  src/utils/macros/routes.js
Labels: bug

#429 Issue/428/hide wrong email error in remind password
  src/components/pages/remind-password.vue
  src/utils/api-response-service.js
  src/utils/error-message.js
Labels: improvement, security

#433 #430 Remove logout on lost connection
  src/dictionary/language/pl.js
  src/utils/api-response-service.js
  src/utils/error-message.js
Labels: bug

#434 Issue/431/cannot open popup map after edit point position
  package.json
  src/api/real/event-controller.js
  src/components/app.vue
  src/components/organisms/admin/set-point-position.vue
  src/components/organisms/map.vue
  src/components/pages/map.vue
  src/components/templates/page.vue
  src/map/createFeatures.js
  src/structures/map-point.js
Labels: bug, improvement

#420 #419 Bump version v1.2.3
  CHANGELOG.md
  package.json
Labels: documentation

#435 Release v1.2.3
  CHANGELOG.md
  controllers/user/remind.js
  controllers/user/user.js
  lib/mail.js
  lib/mail/mail.js
  lib/mail/mailHtmlContent.js
  lib/security/loginOnMultipleDevices.js
  package.json
  src/api/real/event-controller.js
  src/components/app.vue
  src/components/molecules/clock.vue
  src/components/organisms/admin/set-point-position.vue
  src/components/organisms/guide.vue
  src/components/organisms/map.vue
  src/components/pages/map.vue
  src/components/pages/remind-password.vue
  src/components/templates/page.vue
  src/dictionary/language/pl.js
  src/map/createFeatures.js
  src/structures/map-point.js
  src/style/components/atoms/icon/clock.sass
  src/style/components/atoms/icon/footer/big.sass
  src/style/components/molecules/clock.sass
  src/style/components/molecules/grid/temporary-points.sass
  src/style/components/organisms/footer.sass
  src/utils/api-response-service.js
  src/utils/error-message.js
  src/utils/macros/routes.js
  webpack.common.js
Labels: documentation

#437 #410 Add HEAD routing in /user/activation/:key and /user/remind/:key
  controllers/user/activation.js
  controllers/user/remind.js
Labels: bug

#438 #436 Redirect to map after collecting point
  src/components/pages/collect-point.vue
Labels: improvement

#440 Issue/439/bump v1.2.4
  CHANGELOG.md
  README.md
  package.json
Labels: documentation

#441 Release v1.2.4
  CHANGELOG.md
  README.md
  controllers/user/activation.js
  controllers/user/remind.js
  package.json
  src/components/pages/collect-point.vue
Labels: documentation
