Repository dbetka/harcmap, pull requests merged in 2021-10, with the labels that each got.

#499 Issue/497/refactor routing and guards
  src/api/real/event-controller.js
  src/api/real/real.js
  src/api/real/user-controller.js
  src/components/molecules/buttons-list-events.vue
  src/components/organisms/events-list.vue
  src/components/organisms/footer.vue
  src/components/organisms/header.vue
  src/components/organisms/menu.vue
  src/components/organisms/popup/event-confirmation.vue
  src/components/organisms/popup/user-details.vue
  src/components/pages/admin/panel.vue
  src/components/pages/collect-point.vue
  src/components/pages/sign-in.vue
  src/components/templates/event-form.vue
  src/components/templates/page.vue
  src/config/http-service.js
  src/config/routes-config.js
  src/dictionary/language/pl.js
  src/index.js
  src/map/create.js
  src/map/index.js
  src/router/guards.js
  src/router/index.js
  src/router/routes.js
  src/router/utils.js
  src/store/all-users.js
  src/structures/app-event.js
  src/utils/api-response-service.js
  src/utils/macros/routes.js
  webpack.common.js
Labels: refactor

#500 Issue/495/refactor dates handling in app
  src/components/molecules/field/date.vue
  src/components/molecules/field/datetime.vue
  src/components/molecules/row/point.vue
  src/components/molecules/table-row/timeout-points.vue
  src/components/organisms/admin/set-point-position.vue
  src/components/organisms/events-list.vue
  src/components/organisms/guide.vue
  src/components/organisms/popup/event-confirmation.vue
  src/components/organisms/popup/user-details.vue
  src/components/pages/start.vue
  src/components/pages/timeout-points.vue
  src/components/templates/event-form.vue
  src/components/templates/point-form.vue
  src/components/templates/start.vue
  src/config/event-config.js
  src/config/general-config.js
  src/config/users-config.js
  src/map/popup.js
  src/store/event-modules/map.js
  src/store/event-modules/points.js
  src/store/event.js
  src/utils/api-response-service.js
  src/utils/array.js
  src/utils/auto-update.js
  src/utils/date.js
  src/utils/event.js
  src/utils/first-login.js
  src/utils/macros.js
  src/utils/point.js
  src/utils/request.js
  webpack.common.js
Labels: current, refactor

#514 Issue/496/add possible to use typescript
  client/package.json
  client/src/router/index.js
  client/src/utils/promise.js
  client/src/utils/promise.ts
  client/tsconfig.json
  client/webpack.common.js
  client/webpack/rules.js
Labels: improvement

#512 #511 Add recomended solution for hiding navigation duplicated errors
  client/src/router/index.js
Labels: bug

#510 Issue/508/rename window api and fix api imports
  README.md
  client/src/components/organisms/map.vue
  client/src/config/dev-tools.js
  client/src/config/index.js
  client/src/index.js
  client/src/store/all-users.js
  client/src/store/event-modules/points.js
  client/src/store/event.js
  client/src/store/user.js
  client/src/utils/auto-update.js
  client/src/utils/dev-mode/auto-login.js
Labels: bug, improvement

#520 Issue/515/aliases in ts
  .eslintrc
  client/tsconfig.json
  package.json
Labels: bug
