Repository dbetka/harcmap, pull requests merged in 2021-02, with the labels that each got.

#248 #162 Refactor user controller and much more(libs, other controllers).…
  app.js
  config/mongodb/local.js
  controllers/event.js
  controllers/pointCategories.js
  controllers/pointCollect.js
  controllers/user.js
  controllers/user/activation.js
  controllers/user/index.js
  controllers/user/login.js
  controllers/user/remind.js
  controllers/user/user.js
  lib/mail.js
  lib/mongodb.js
  lib/passportConfig.js
  lib/utils.js
  lib/validateCodes.js
Labels: performance

#273 #271 Add map refresh time in event endpoints
  bin/prepareEvent.js
  config/mongodb/local.js
  controllers/event.js
  src/components/pages/sign-in.vue
  src/store/event.js
  src/structures/app-event.js
  src/utils/auto-update.js
  src/utils/macros/errors.js
Labels: to do

#287 #286 Fix collected points appearance
  src/map/create.js
  src/map/createFeatures.js
Labels: bug

#288 #259 Change error view appearance
  public/img/treasure-map.jpg
  src/components/pages/error.vue
  src/dictionary/language/pl.js
Labels: improvement

#293 #289 Fix changing page title
  src/components/templates/page.vue
Labels: bug, current

#294 Issue/274/fix select field
  src/components/molecules/select.vue
  src/style/components/atoms/field.sass
  src/style/components/atoms/input/select.sass
  src/style/components/molecules/options.sass
  src/style/extends/field-animation.sass
Labels: bug, current

#291 Issue/269/create success message in set map position view
  src/components/molecules/banner-map.vue
  src/components/organisms/admin/set-map-position.vue
  src/dictionary/language/pl.js
  src/style/components/molecules/banner/message-success.sass
Labels: current

#299 Issue/296/create admin panel
  src/components/organisms/footer.vue
  src/components/pages/admin/panel.vue
  src/components/pages/sign-in.vue
  src/dictionary/language/pl.js
  src/router/routes.js
  src/utils/macros/routes.js
Labels: improvement
