Repository dbetka/harcmap, pull requests merged in 2021-11, with the labels that each got.

#528 Issue/526/trim fields in login and registration
  client/src/components/pages/sign-in.vue
  client/src/components/pages/sign-up.vue
Labels: bug, current, improvement

#534 Issue/527/add user role icons in users list
  client/src/components/pages/admin/users-list.vue
  client/src/style/auto-import/components/molecules/grid/search-user.sass
Labels: improvement

#538 issue/537/correcting and narrowing field types for data validation
  server/endpoints/v1/users/methods/get-users.js
  server/libs/common-schemas.js
Labels: current, security

#543 Issue/536/advance game config
  client/src/components/atoms/checkbox.vue
  client/src/components/molecules/field/datetime.vue
  client/src/components/organisms/admin/game-advanced-rules.vue
  client/src/components/pages/admin/edit-event.vue
  client/src/components/templates/event-form.vue
  client/src/config/dev-tools.js
  client/src/config/event-config.js
  client/src/config/event-config.ts
  client/src/dictionary/language/pl.js
  client/src/models/common.ts
  client/src/models/game-rules.ts
  client/src/models/routes.ts
  client/src/router/utils.ts
  client/src/structures/app-event.js
  client/src/style/__cache__/index.sass
  client/src/style/auto-import/components/atoms/text/assist.sass
  client/src/utils/enum.ts
  client/src/utils/game-rules.ts
  client/src/utils/translations.js
  client/src/utils/translations.ts
  client/tsconfig.json
Labels: improvement

#539 Issue/535/create team page
  client/src/components/molecules/table-row/team-row.vue
  client/src/components/organisms/menu.vue
  client/src/components/pages/team-view.vue
  client/src/config/routes-config.ts
  client/src/config/users-config.js
  client/src/dictionary/language/pl.js
  client/src/router/routes.js
  client/src/style/__cache__/index.sass
  client/src/style/auto-import/components/molecules/grid/team-view.sass
Labels: current

#556 Issue/555/replace objectid method
  server/endpoints/v1/users/methods/get-user.js
  server/endpoints/v1/users/methods/get-users.js
  server/endpoints/v1/users/methods/update-user.js
  server/libs/mongodb.js
  server/libs/passport-configs.js
  server/tests/utils/database.js
Labels: current, improvement

#557 Issue/554/sorting in aggregations
  server/aggregations/get-user.js
  server/aggregations/get-users.js
Labels: current, improvement

#558 Issue/553/check account activation
  server/aggregations/get-user.js
  server/bin/mongodb/default-dump.js
  server/bin/mongodb/init/default.dump.js
  server/endpoints/v1/auth/specs/auth-sign-up.spec.js
  server/endpoints/v1/categories/specs/categories.spec.js
  server/endpoints/v1/events/methods/update-event.js
  server/endpoints/v1/events/specs/join-event.spec.js
  server/libs/errors/codes.js
  server/libs/passport-configs.js
Labels: current, improvement
