Repository dbetka/harcmap, pull requests merged in 2022-05, with the labels that each got.

#622 Issue/621/small app logic changes
  client/src/api/real/auth-controller.ts
  client/src/api/real/event-controller.ts
  client/src/components/molecules/row/point.vue
  client/src/components/organisms/collected-points.vue
  client/src/components/organisms/events-list.vue
  client/src/components/organisms/header.vue
  client/src/components/organisms/menu.vue
  client/src/components/organisms/popup/event-confirmation.vue
  client/src/components/pages/add-event.vue
  client/src/components/pages/admin/scoreboard.vue
  client/src/components/pages/admin/users-list.vue
  client/src/dictionary/language/plPL.ts
  client/src/map/index.js
  client/src/models/dtos/event.ts
  client/src/models/utils/mapper.ts
  client/src/store/event-modules/categories.js
  client/src/store/event-modules/points-statistics.js
  client/src/store/event.js
  client/src/style/auto-import/components/molecules/grid/point.sass
  client/src/utils/dev-mode/feature-toggle.ts
  client/src/utils/enter-event.ts
Labels: improvement

#620 Issue/612/teams tracks on map for admin
  client/src/api/real/event-controller.ts
  client/src/components/organisms/popup/event-confirmation.vue
  client/src/components/pages/join-event.vue
  client/src/config/users-config.ts
  client/src/dictionary/language/plPL.ts
  client/src/map/factories/linesFeature.ts
  client/src/map/factories/pointsFeature.ts
  client/src/models/dtos/team.ts
  client/src/models/team.ts
  client/src/store/event.js
  client/src/store/team.ts
Labels: improvement

#602 Issue/599/map settings popup
  client/src/components/organisms/map-settings-toggler.vue
  client/src/components/organisms/map-settings.vue
  client/src/components/organisms/map.vue
  client/src/components/organisms/popup/map.vue
  client/src/components/pages/map.vue
  client/src/map/config.ts
  client/src/map/factories/linesFeature.ts
  client/src/map/factories/pointsFeature.ts
  client/src/map/features/myPosition.ts
  client/src/map/index.js
  client/src/store/index.js
  client/src/store/map-popup.js
  client/src/utils/dev-mode/feature-toggle.ts
Labels: improvement

#625 issue/624/fix mocks
  client/src/map/factories/pointsFeature.ts
  server/bin/mongodb/custom-dump/categories.dump.js
  server/bin/mongodb/custom-dump/points.dump.js
  server/bin/mongodb/custom-dump/teams.dump.js
  server/bin/mongodb/default-dump/categories.dump.js
  server/bin/mongodb/default-dump/points.dump.js
  server/bin/mongodb/default-dump/teams.dump.js
Labels: bug

#597 Issue/583/create user data edition endpoint
  server/app.js
  server/endpoints/v1/user/index.js
  server/endpoints/v1/user/methods/edit-user.js
  server/endpoints/v1/user/request-schema.js
  server/endpoints/v1/user/specs/user.spec.js
  server/endpoints/v1/user/specs/user.swagger.yml
  server/libs/common-schemas.js
  server/libs/errors/codes.js
  server/libs/permissions/endpoints-settings.js
  server/specs/swagger-components/properties.swagger.yml
  server/swagger.config.js
Labels: documentation, improvement

#629 Feature/628/fix points on map logic
  client/src/components/organisms/map-settings.vue
  client/src/map/factories/pointsFeature.ts
  client/src/utils/date.ts
  client/src/utils/dev-mode/auto-login.js
  client/src/utils/point.js
Labels: bug, improvement

#627 Feature/626/team color in app
  client/src/components/molecules/select.vue
  client/src/components/organisms/popup/map.vue
  client/src/components/pages/admin/point-category-list.vue
  client/src/components/pages/join-event.vue
  client/src/components/pages/team-view.vue
  client/src/components/templates/point-category-form.vue
  client/src/config/map-point-popup-config.ts
  client/src/dictionary/language/plPL.ts
  client/src/utils/macros/colors.ts
Labels: improvement

#633 Issue/632/refactor download event
  client/src/config/users-config.ts
  client/src/store/event.js
  client/src/utils/point-category.ts
Labels: performance, improvement

#639 Issue/638/fix user data modification endpoint
  server/aggregations/get-user-events.js
  server/endpoints/v1/user/index.js
  server/endpoints/v1/user/methods/edit-user.js
  server/endpoints/v1/user/request-schema.js
  server/endpoints/v1/user/specs/user.spec.js
Labels: improvement
