Repository dbetka/harcmap, pull requests merged in 2022-04, with the labels that each got.

#591 Issue/590/point category improvements
  client/src/components/pages/admin/edit-point-category.vue
  client/src/components/pages/admin/point-category-list.vue
  client/src/dictionary/language/plPL.ts
  client/src/style/auto-import/components/molecules/grid/point-category-list.sass
Labels: bug, improvement

#587 Issue/586/fix frontend router before each process
  client/src/components/organisms/map.vue
  client/src/components/pages/auth/sign-in.vue
  client/src/map/index.js
  client/src/map/popup.js
  client/src/router/index.js
  client/src/store/user.ts
  client/src/utils/enter-event.ts
  client/src/utils/session.js
  client/src/utils/storage.ts
  client/src/utils/url.ts
Labels: bug

#595 Issue/594/geolocation distance detection
  client/src/api/real/event-controller.ts
  client/src/api/real/point-category-controller.ts
  client/src/components/organisms/admin/game-advanced-rules.vue
  client/src/components/organisms/map.vue
  client/src/components/organisms/popup/map.vue
  client/src/components/pages/admin/edit-event.vue
  client/src/components/templates/event-form.vue
  client/src/config/geolocation-config.ts
  client/src/map/config.ts
  client/src/map/createLinesFeature.js
  client/src/map/factories/featureCommon.ts
  client/src/map/factories/linesFeature.ts
  client/src/map/factories/myPositionFeature.ts
  client/src/map/factories/pointsFeature.ts
  client/src/map/features/lines.ts
  client/src/map/features/myPosition.ts
  client/src/map/features/points.ts
  client/src/map/index.js
  client/src/map/lines.js
  client/src/map/points.js
  client/src/models/dtos/event.ts
  client/src/models/dtos/point.ts
  client/src/models/event.ts
  client/src/models/point.ts
  client/src/models/utils/mapper.ts
  client/src/store/event.js
  client/src/utils/dev-mode/feature-toggle.ts
  client/src/utils/game-rules.ts
Labels: improvement

#596 Issue/582/add npm husky
  .husky/pre-push
  package.json
  server/package.json
Labels: tests

#601 Issue/600/block menu slide before event
  client/src/components/templates/page.vue
Labels: bug

#605 Issue/603/upgrade all npm dependencies april 2022
  client/android/build.gradle
  client/android/gradle/wrapper/gradle-wrapper.properties
  client/package.json
  client/src/map/features/points.ts
  package.json
Labels: maintenance

#607 issue/606/Fix displaying errors and warnings while making build
  client/package.json
  client/webpack/config.common.js
  client/webpack/configs/eslint-config.js
  client/webpack/configs/html-webpack-config.js
  client/webpack/configs/image-config.js
  client/webpack/plugins/app-console-frame.js
  client/webpack/plugins/progress-bar-config.js
Labels: bug

#614 issue/613/webpack config is unable to read by IDE
  client/package.json
Labels: bug

#616 Issue/615/fix routing and user
  server/bin/mongodb/restore-database-to-default.js
  server/bin/mongodb/utils.js
  server/endpoints/v1/events/specs/event.spec.js
  server/libs/utils/check-key.js
  server/package.json
  server/tests/utils/test-endpoint.js
Labels: bug

#617 Issue/609/cypress tests with emails poc
  client/cypress/cypress.local.json
  client/cypress/integration/collectPoint_spec.ts
  client/cypress/integration/joinEvent_spec.ts
  client/cypress/integration/registration_spec.ts
  client/cypress/integration/resetPassword_spec.ts
  client/cypress/integration/sample_spec.js
  client/cypress/plugins/index.js
  client/cypress/support/index.ts
  client/cypress/utils/email.ts
  client/cypress/utils/init-test.ts
  client/cypress/utils/interceptions.ts
  client/package.json
Labels: improvement
