Repository dbetka/harcmap, pull requests merged in 2022-07, with the labels that each got.

#651 #648 Fix semicolon problem for windows
  server/package.json
Labels: bug

#643 Issue/642/fix share event by apps on mobile app
  client/README.md
  client/android/app/capacitor.build.gradle
  client/android/app/src/main/AndroidManifest.xml
  client/android/app/src/main/assets/capacitor.config.json
  client/android/app/src/main/assets/capacitor.plugins.json
  client/android/capacitor.settings.gradle
  client/capacitor.config.json
  client/ios/App/App.xcodeproj/project.pbxproj
  client/ios/App/App/capacitor.config.json
  client/ios/App/Podfile
  client/package.json
  client/src/capacitor-config.js
  client/src/components/molecules/loading-app.vue
  client/src/components/organisms/loading-app.vue
  client/src/components/organisms/share-for-user-type.vue
  client/src/components/pages/share-team.vue
  client/src/config/app-env.ts
  client/src/env.d.ts
  client/src/index.js
  client/src/store/event.js
  client/src/store/invitations.ts
  client/webpack/options/env.js
  package.json
Labels: bug, improvement, learn

#650 issue/649/Create account and add no-reply@harcmap.pl mail to envs
  server/.env.local
  server/.env.tests
Labels: improvement
